version: "4.0"
services:
  postgres:
   image: postgres
   restart: always
   container_name: postgres
   ports:
    - 5555:5432
   environment:
     POSTGRES_USER: ahmed
     POSTGRES_PASSWORD: password
     POSTGRES_DB: mzad_db
  mongo:
   image: mongo
   restart: always
   container_name: mongo
   ports:
    - 5556:27017
   environment:
    - MONGO_INITDB_ROOT_USERNAME=ahmed
    - MONGO_INITDB_ROOT_PASSWORD=password